name: Despliegue
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:

  build:
    name: Checkout repository

    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}

    name: ionic integrations enable capacitor, ionic build, npx cap add ios,  npx cap add android, npx cap copy 
    uses: actions/upload-artifact@v1  
      run: |
        ionic integrations enable capacitor
        ionic build
        npx cap add ios
        npx cap add android
        npx cap copy 